SELECT COUNT(a.FIRST_NAME) AS BOOK_COUNT, a.FIRST_NAME, a.LAST_NAME
FROM AUTHOR a
JOIN AUTHOR_BOOK ab ON a.ID = ab.ID_AUTHOR
JOIN BOOK b ON b.id = ab.ID_BOOK
GROUP BY a.FIRST_NAME, a.LAST_NAME
HAVING COUNT(a.FIRST_NAME) > 3